sudo: required

services:
  - docker

before_install:
  - docker build -t abwin10/docker-react -f Dockerfile.dev .

cache:
  directories:
    - node_modules


script:
  - docker run abwin10/docker-react npm run test